package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/_GestionUsuariosIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public class _GestionUsuariosIntStub extends org.omg.CORBA.portable.ObjectImpl implements s_gestion_usuarios.sop_corba.GestionUsuariosInt
{

  public boolean registrarUsuario (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarUsuario", true);
                s_gestion_usuarios.sop_corba.UsuarioDTOHelper.write ($out, objUsuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarUsuario (objUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarUsuario

  public boolean consultarUsuario (int id, s_gestion_usuarios.sop_corba.UsuarioDTOHolder objUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarUsuario", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objUsuario.value = s_gestion_usuarios.sop_corba.UsuarioDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarUsuario (id, objUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarUsuario

  public void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCallback", true);
                s_gestion_usuarios.sop_corba.AdmCllbckIntHelper.write ($out, objCllbck);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarCallback (objCllbck        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCallback

  public s_gestion_usuarios.sop_corba.UsuarioDTO[] listaUsuariosF ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaUsuariosF", true);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.UsuarioDTO $result[] = s_gestion_usuarios.sop_corba.arrayUsuarioDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaUsuariosF (        );
            } finally {
                _releaseReply ($in);
            }
  } // listaUsuariosF

  public void registrarPlanFisico (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] planFisicoCompleto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPlanFisico", true);
                s_gestion_usuarios.sop_corba.UsuarioDTOHelper.write ($out, objUsuario);
                s_gestion_usuarios.sop_corba.HashMapPrSmDTOHelper.write ($out, planFisicoCompleto);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarPlanFisico (objUsuario, planFisicoCompleto        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPlanFisico

  public s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] consultarProgramaCompleto (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarProgramaCompleto", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO $result[] = s_gestion_usuarios.sop_corba.HashMapPrSmDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarProgramaCompleto (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarProgramaCompleto

  public void registrarValoracion (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarValoracion", true);
                s_gestion_usuarios.sop_corba.UsuarioDTOHelper.write ($out, objUsuario);
                s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.write ($out, objValoracion);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarValoracion (objUsuario, objValoracion        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarValoracion

  public s_seguimiento_usuarios.sop_corba.ValoracionDTO consultarValoracion (int objUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarValoracion", true);
                $out.write_long (objUsuario);
                $in = _invoke ($out);
                s_seguimiento_usuarios.sop_corba.ValoracionDTO $result = s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarValoracion (objUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarValoracion

  public int registrarAsistencia (s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarAsistencia", true);
                s_seguimiento_usuarios.sop_corba.AsistenciaDTOHelper.write ($out, objAsistencia);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarAsistencia (objAsistencia        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarAsistencia

  public s_seguimiento_usuarios.sop_corba.AsistenciaDTO[] consultarAsistenciasUsuario (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAsistenciasUsuario", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_seguimiento_usuarios.sop_corba.AsistenciaDTO $result[] = s_gestion_usuarios.sop_corba.arrayAsistenciaDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAsistenciasUsuario (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAsistenciasUsuario

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuariosInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionUsuariosIntStub
