package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/AdmCllbckInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public interface AdmCllbckInt extends AdmCllbckIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdmCllbckInt
