package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/AdmCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public interface AdmCllbckIntOperations 
{
  void notificar (String nombreCompleto, int id);
} // interface AdmCllbckIntOperations
