package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/CredencialDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public final class CredencialDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;
  public String clave = null;

  public CredencialDTO ()
  {
  } // ctor

  public CredencialDTO (String _usuario, String _clave)
  {
    usuario = _usuario;
    clave = _clave;
  } // ctor

} // class CredencialDTO
