package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public class GestionUsuariosIntPOATie extends GestionUsuariosIntPOA
{

  // Constructors

  public GestionUsuariosIntPOATie ( s_gestion_usuarios.sop_corba.GestionUsuariosIntOperations delegate ) {
      this._impl = delegate;
  }
  public GestionUsuariosIntPOATie ( s_gestion_usuarios.sop_corba.GestionUsuariosIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public s_gestion_usuarios.sop_corba.GestionUsuariosIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (s_gestion_usuarios.sop_corba.GestionUsuariosIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean registrarUsuario (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario)
  {
    return _impl.registrarUsuario(objUsuario);
  } // registrarUsuario

  public boolean consultarUsuario (int id, s_gestion_usuarios.sop_corba.UsuarioDTOHolder objUsuario)
  {
    return _impl.consultarUsuario(id, objUsuario);
  } // consultarUsuario

  public void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck)
  {
    _impl.registrarCallback(objCllbck);
  } // registrarCallback

  public s_gestion_usuarios.sop_corba.UsuarioDTO[] listaUsuariosF ()
  {
    return _impl.listaUsuariosF();
  } // listaUsuariosF

  public void registrarPlanFisico (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] planFisicoCompleto)
  {
    _impl.registrarPlanFisico(objUsuario, planFisicoCompleto);
  } // registrarPlanFisico

  public s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] consultarProgramaCompleto (int id)
  {
    return _impl.consultarProgramaCompleto(id);
  } // consultarProgramaCompleto

  public void registrarValoracion (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion)
  {
    _impl.registrarValoracion(objUsuario, objValoracion);
  } // registrarValoracion

  public s_seguimiento_usuarios.sop_corba.ValoracionDTO consultarValoracion (int objUsuario)
  {
    return _impl.consultarValoracion(objUsuario);
  } // consultarValoracion

  public int registrarAsistencia (s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia)
  {
    return _impl.registrarAsistencia(objAsistencia);
  } // registrarAsistencia

  public s_seguimiento_usuarios.sop_corba.AsistenciaDTO[] consultarAsistenciasUsuario (int id)
  {
    return _impl.consultarAsistenciasUsuario(id);
  } // consultarAsistenciasUsuario

  private s_gestion_usuarios.sop_corba.GestionUsuariosIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionUsuariosIntPOATie
