package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public interface GestionUsuariosIntOperations 
{
  boolean registrarUsuario (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario);
  boolean consultarUsuario (int id, s_gestion_usuarios.sop_corba.UsuarioDTOHolder objUsuario);
  void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck);
  s_gestion_usuarios.sop_corba.UsuarioDTO[] listaUsuariosF ();
  void registrarPlanFisico (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] planFisicoCompleto);
  s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] consultarProgramaCompleto (int id);
  void registrarValoracion (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion);
  s_seguimiento_usuarios.sop_corba.ValoracionDTO consultarValoracion (int objUsuario);
  int registrarAsistencia (s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia);
  s_seguimiento_usuarios.sop_corba.AsistenciaDTO[] consultarAsistenciasUsuario (int id);
} // interface GestionUsuariosIntOperations
