package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionPersonalIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public interface GestionPersonalIntOperations 
{
  void registrarPersonal (s_gestion_usuarios.sop_corba.PersonalDTO objPersonal);
  boolean consultarPersonal (int id, s_gestion_usuarios.sop_corba.PersonalDTOHolder objPersonal);
  int abrirSesion (s_gestion_usuarios.sop_corba.CredencialDTO objCredencial);
  boolean editarPersonal (int id, s_gestion_usuarios.sop_corba.PersonalDTO objPersonalNuevosDatos);
  boolean eliminarPersonal (int id);
} // interface GestionPersonalIntOperations
