package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public abstract class GestionUsuariosIntPOA extends org.omg.PortableServer.Servant
 implements s_gestion_usuarios.sop_corba.GestionUsuariosIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarUsuario", new java.lang.Integer (0));
    _methods.put ("consultarUsuario", new java.lang.Integer (1));
    _methods.put ("registrarCallback", new java.lang.Integer (2));
    _methods.put ("listaUsuariosF", new java.lang.Integer (3));
    _methods.put ("registrarPlanFisico", new java.lang.Integer (4));
    _methods.put ("consultarProgramaCompleto", new java.lang.Integer (5));
    _methods.put ("registrarValoracion", new java.lang.Integer (6));
    _methods.put ("consultarValoracion", new java.lang.Integer (7));
    _methods.put ("registrarAsistencia", new java.lang.Integer (8));
    _methods.put ("consultarAsistenciasUsuario", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionUsuariosInt/registrarUsuario
       {
         s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario = s_gestion_usuarios.sop_corba.UsuarioDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarUsuario (objUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/GestionUsuariosInt/consultarUsuario
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.UsuarioDTOHolder objUsuario = new s_gestion_usuarios.sop_corba.UsuarioDTOHolder ();
         boolean $result = false;
         $result = this.consultarUsuario (id, objUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         s_gestion_usuarios.sop_corba.UsuarioDTOHelper.write (out, objUsuario.value);
         break;
       }

       case 2:  // sop_corba/GestionUsuariosInt/registrarCallback
       {
         s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck = s_gestion_usuarios.sop_corba.AdmCllbckIntHelper.read (in);
         this.registrarCallback (objCllbck);
         out = $rh.createReply();
         break;
       }

       case 3:  // sop_corba/GestionUsuariosInt/listaUsuariosF
       {
         s_gestion_usuarios.sop_corba.UsuarioDTO $result[] = null;
         $result = this.listaUsuariosF ();
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.arrayUsuarioDTOHelper.write (out, $result);
         break;
       }

       case 4:  // sop_corba/GestionUsuariosInt/registrarPlanFisico
       {
         s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario = s_gestion_usuarios.sop_corba.UsuarioDTOHelper.read (in);
         s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO planFisicoCompleto[] = s_gestion_usuarios.sop_corba.HashMapPrSmDTOHelper.read (in);
         this.registrarPlanFisico (objUsuario, planFisicoCompleto);
         out = $rh.createReply();
         break;
       }

       case 5:  // sop_corba/GestionUsuariosInt/consultarProgramaCompleto
       {
         int id = in.read_long ();
         s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO $result[] = null;
         $result = this.consultarProgramaCompleto (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.HashMapPrSmDTOHelper.write (out, $result);
         break;
       }

       case 6:  // sop_corba/GestionUsuariosInt/registrarValoracion
       {
         s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario = s_gestion_usuarios.sop_corba.UsuarioDTOHelper.read (in);
         s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion = s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.read (in);
         this.registrarValoracion (objUsuario, objValoracion);
         out = $rh.createReply();
         break;
       }

       case 7:  // sop_corba/GestionUsuariosInt/consultarValoracion
       {
         int objUsuario = in.read_long ();
         s_seguimiento_usuarios.sop_corba.ValoracionDTO $result = null;
         $result = this.consultarValoracion (objUsuario);
         out = $rh.createReply();
         s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.write (out, $result);
         break;
       }

       case 8:  // sop_corba/GestionUsuariosInt/registrarAsistencia
       {
        s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia = s_seguimiento_usuarios.sop_corba.AsistenciaDTOHelper.read (in);
         int $result = (int)0;
         $result = this.registrarAsistencia (objAsistencia);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // sop_corba/GestionUsuariosInt/consultarAsistenciasUsuario
       {
         int id = in.read_long ();
         s_seguimiento_usuarios.sop_corba.AsistenciaDTO $result[] = null;
         $result = this.consultarAsistenciasUsuario (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.arrayAsistenciaDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuariosInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionUsuariosInt _this() 
  {
    return GestionUsuariosIntHelper.narrow(
    super._this_object());
  }

  public GestionUsuariosInt _this(org.omg.CORBA.ORB orb) 
  {
    return GestionUsuariosIntHelper.narrow(
    super._this_object(orb));
  }


} // class GestionUsuariosIntPOA
