package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/KeyValEjDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./gusuarios.idl
* lunes 7 de marzo de 2022 12:17:04 PM COT
*/

public final class KeyValEjDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public s_gestion_usuarios.sop_corba.EjercicioDTO value[] = null;

  public KeyValEjDTO ()
  {
  } // ctor

  public KeyValEjDTO (String _key, s_gestion_usuarios.sop_corba.EjercicioDTO[] _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class KeyValEjDTO
