package s_seguimiento_usuarios.sop_corba;

import s_gestion_usuarios.sop_corba.UsuarioDTO;

/**
* s_seguimiento_usuarios/sop_corba/_GestionProgramaFisicoUsuarioIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public class _GestionProgramaFisicoUsuarioIntStub extends org.omg.CORBA.portable.ObjectImpl implements s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioInt
{

  public void registrarPlanFisico (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] planFisicoCompleto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPlanFisico", true);
                s_gestion_usuarios.sop_corba.UsuarioDTOHelper.write ($out, objUsuario);
                s_seguimiento_usuarios.sop_corba.HashMapPrSmDTOHelper.write ($out, planFisicoCompleto);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarPlanFisico (objUsuario, planFisicoCompleto        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPlanFisico

  public s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] consultarProgramaCompleto (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarProgramaCompleto", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO $result[] = s_seguimiento_usuarios.sop_corba.HashMapPrSmDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarProgramaCompleto (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarProgramaCompleto

  public void registrarValoracion (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarValoracion", true);
                s_gestion_usuarios.sop_corba.UsuarioDTOHelper.write ($out, objUsuario);
                s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.write ($out, objValoracion);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarValoracion (objUsuario, objValoracion        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarValoracion

  public s_seguimiento_usuarios.sop_corba.ValoracionDTO consultarValoracion (int objUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarValoracion", true);
                $out.write_long (objUsuario);
                $in = _invoke ($out);
                s_seguimiento_usuarios.sop_corba.ValoracionDTO $result = s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarValoracion (objUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarValoracion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionProgramaFisicoUsuarioInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }



} // class _GestionProgramaFisicoUsuarioIntStub
