package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/EjercicioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public final class EjercicioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int repeticiones = (int)0;
  public double pese = (double)0;

  public EjercicioDTO ()
  {
  } // ctor

  public EjercicioDTO (String _nombre, int _repeticiones, double _pese)
  {
    nombre = _nombre;
    repeticiones = _repeticiones;
    pese = _pese;
  } // ctor

} // class EjercicioDTO
