package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionProgramaFisicoUsuarioIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public interface GestionProgramaFisicoUsuarioIntOperations 
{
  void registrarPlanFisico (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] planFisicoCompleto);
  s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] consultarProgramaCompleto (int id);
  void registrarValoracion (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion);
  s_seguimiento_usuarios.sop_corba.ValoracionDTO consultarValoracion (int objUsuario);
} // interface GestionProgramaFisicoUsuarioIntOperations
