package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionAsistenciaIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public abstract class GestionAsistenciaIntPOA extends org.omg.PortableServer.Servant
 implements s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarAsistencia", new java.lang.Integer (0));
    _methods.put ("consultarAsistenciasUsuario", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionAsistenciaInt/registrarAsistencia
       {
         s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia = s_seguimiento_usuarios.sop_corba.AsistenciaDTOHelper.read (in);
         int $result = (int)0;
         $result = this.registrarAsistencia (objAsistencia);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // sop_corba/GestionAsistenciaInt/consultarAsistenciasUsuario
       {
         int id = in.read_long ();
         s_seguimiento_usuarios.sop_corba.AsistenciaDTO $result[] = null;
         $result = this.consultarAsistenciasUsuario (id);
         out = $rh.createReply();
         s_seguimiento_usuarios.sop_corba.arrayAsistenciaDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionAsistenciaInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionAsistenciaInt _this() 
  {
    return GestionAsistenciaIntHelper.narrow(
    super._this_object());
  }

  public GestionAsistenciaInt _this(org.omg.CORBA.ORB orb) 
  {
    return GestionAsistenciaIntHelper.narrow(
    super._this_object(orb));
  }


} // class GestionAsistenciaIntPOA
