package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionProgramaFisicoUsuarioIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public class GestionProgramaFisicoUsuarioIntPOATie extends GestionProgramaFisicoUsuarioIntPOA
{

  // Constructors

  public GestionProgramaFisicoUsuarioIntPOATie ( s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioIntOperations delegate ) {
      this._impl = delegate;
  }
  public GestionProgramaFisicoUsuarioIntPOATie ( s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registrarPlanFisico (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] planFisicoCompleto)
  {
    _impl.registrarPlanFisico(objUsuario, planFisicoCompleto);
  } // registrarPlanFisico

  public s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO[] consultarProgramaCompleto (int id)
  {
    return _impl.consultarProgramaCompleto(id);
  } // consultarProgramaCompleto

  public void registrarValoracion (s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario, s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion)
  {
    _impl.registrarValoracion(objUsuario, objValoracion);
  } // registrarValoracion

  public s_seguimiento_usuarios.sop_corba.ValoracionDTO consultarValoracion (int objUsuario)
  {
    return _impl.consultarValoracion(objUsuario);
  } // consultarValoracion

  private s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionProgramaFisicoUsuarioIntPOATie
