package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionAsistenciaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public interface GestionAsistenciaIntOperations 
{
  int registrarAsistencia (s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia);
  s_seguimiento_usuarios.sop_corba.AsistenciaDTO[] consultarAsistenciasUsuario (int id);
} // interface GestionAsistenciaIntOperations
