package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionAsistenciaIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public class GestionAsistenciaIntPOATie extends GestionAsistenciaIntPOA
{

  // Constructors

  public GestionAsistenciaIntPOATie ( s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntOperations delegate ) {
      this._impl = delegate;
  }
  public GestionAsistenciaIntPOATie ( s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int registrarAsistencia (s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia)
  {
    return _impl.registrarAsistencia(objAsistencia);
  } // registrarAsistencia

  public s_seguimiento_usuarios.sop_corba.AsistenciaDTO[] consultarAsistenciasUsuario (int id)
  {
    return _impl.consultarAsistenciasUsuario(id);
  } // consultarAsistenciasUsuario

  private s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionAsistenciaIntPOATie
