package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionAsistenciaIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

abstract public class GestionAsistenciaIntHelper
{
  private static String  _id = "IDL:sop_corba/GestionAsistenciaInt:1.0";

  public static void insert (org.omg.CORBA.Any a, s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (s_seguimiento_usuarios.sop_corba.GestionAsistenciaIntHelper.id (), "GestionAsistenciaInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionAsistenciaIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt)
      return (s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      s_seguimiento_usuarios.sop_corba._GestionAsistenciaIntStub stub = new s_seguimiento_usuarios.sop_corba._GestionAsistenciaIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt)
      return (s_seguimiento_usuarios.sop_corba.GestionAsistenciaInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      s_seguimiento_usuarios.sop_corba._GestionAsistenciaIntStub stub = new s_seguimiento_usuarios.sop_corba._GestionAsistenciaIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
