package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionProgramaFisicoUsuarioIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public abstract class GestionProgramaFisicoUsuarioIntPOA extends org.omg.PortableServer.Servant
 implements s_seguimiento_usuarios.sop_corba.GestionProgramaFisicoUsuarioIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarPlanFisico", new java.lang.Integer (0));
    _methods.put ("consultarProgramaCompleto", new java.lang.Integer (1));
    _methods.put ("registrarValoracion", new java.lang.Integer (2));
    _methods.put ("consultarValoracion", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionProgramaFisicoUsuarioInt/registrarPlanFisico
       {
        s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario = s_gestion_usuarios.sop_corba.UsuarioDTOHelper.read (in);
         s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO planFisicoCompleto[] = s_seguimiento_usuarios.sop_corba.HashMapPrSmDTOHelper.read (in);
         this.registrarPlanFisico (objUsuario, planFisicoCompleto);
         out = $rh.createReply();
         break;
       }

       case 1:  // sop_corba/GestionProgramaFisicoUsuarioInt/consultarProgramaCompleto
       {
         int id = in.read_long ();
         s_seguimiento_usuarios.sop_corba.KeyValPrSmDTO $result[] = null;
         $result = this.consultarProgramaCompleto (id);
         out = $rh.createReply();
         s_seguimiento_usuarios.sop_corba.HashMapPrSmDTOHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/GestionProgramaFisicoUsuarioInt/registrarValoracion
       {
        s_gestion_usuarios.sop_corba.UsuarioDTO objUsuario = s_gestion_usuarios.sop_corba.UsuarioDTOHelper.read (in);
         s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion = s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.read (in);
         this.registrarValoracion (objUsuario, objValoracion);
         out = $rh.createReply();
         break;
       }

       case 3:  // sop_corba/GestionProgramaFisicoUsuarioInt/consultarValoracion
       {
         int objUsuario = in.read_long ();
         s_seguimiento_usuarios.sop_corba.ValoracionDTO $result = null;
         $result = this.consultarValoracion (objUsuario);
         out = $rh.createReply();
         s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionProgramaFisicoUsuarioInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionProgramaFisicoUsuarioInt _this() 
  {
    return GestionProgramaFisicoUsuarioIntHelper.narrow(
    super._this_object());
  }

  public GestionProgramaFisicoUsuarioInt _this(org.omg.CORBA.ORB orb) 
  {
    return GestionProgramaFisicoUsuarioIntHelper.narrow(
    super._this_object(orb));
  }


} // class GestionProgramaFisicoUsuarioIntPOA
