package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/KeyValPrSmDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public final class KeyValPrSmDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public s_seguimiento_usuarios.sop_corba.ProgramaSemanaDTO value = null;

  public KeyValPrSmDTO ()
  {
  } // ctor

  public KeyValPrSmDTO (String _key, s_seguimiento_usuarios.sop_corba.ProgramaSemanaDTO _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class KeyValPrSmDTO
