package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/ValoracionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./susuarios.idl
* lunes 7 de marzo de 2022 12:16:48 PM COT
*/

public final class ValoracionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String fechaValoracion = null;
  public double frecuenciaCardiacaReposo = (double)0;
  public double frecuenciaCardiacaActiva = (double)0;
  public double estattura = (double)0;
  public double brazo = (double)0;
  public double pierna = (double)0;
  public double pecho = (double)0;
  public double cintura = (double)0;

  public ValoracionDTO ()
  {
  } // ctor

  public ValoracionDTO (int _id, String _fechaValoracion, double _frecuenciaCardiacaReposo, double _frecuenciaCardiacaActiva, double _estattura, double _brazo, double _pierna, double _pecho, double _cintura)
  {
    id = _id;
    fechaValoracion = _fechaValoracion;
    frecuenciaCardiacaReposo = _frecuenciaCardiacaReposo;
    frecuenciaCardiacaActiva = _frecuenciaCardiacaActiva;
    estattura = _estattura;
    brazo = _brazo;
    pierna = _pierna;
    pecho = _pecho;
    cintura = _cintura;
  } // ctor

} // class ValoracionDTO
